# Generated by Django 5.0 on 2025-02-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='booking_id',
        ),
    ]
