# Generated by Django 5.0 on 2025-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_booking_payment_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
